cloudmex/Nativo-NFT-UI

package-lock.json
package.json
src/App.js
src/components/Navbar.component.js
src/translations/en/global.json
src/translations/es/global.json
src/utils/near_interaction.js
src/views/gallery.js
src/views/mintNft.view.js

The adaptation of the new methods for mining and obtaining the nfts to generate a gallery was carried out, in the case of the view of creating a new NFT, all references to the collections were eliminated, the labels were removed and the method was modified by adding it to near interaction to be able to mine a new NFT.
On the part of the gallery, the tokensCollection file was taken as a base to generate a gallery of all the NFTs belonging to the native-minter contract, a new pagination method had to be worked on, the one chosen for this has been to implement the infinite scroll Due to how the method that near provides us works to list the tokens, different adaptations were made in the design for this to be displayed correctly.

NM-91 - NM-3 Adaptation of the new standard methods

---

src/views/Detail.view.js
src/views/MisTokens.view.js

Update mynft and nft details views to retrieve info of new contract that is using currently the new standard

My nfts and nft details

---

src/components/transferModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/utils/near_interaction.js
src/views/MisTokens.view.js

The functionality of transfers to my NFTs was added, in order to use this functionality a button was added on each NFT which opens a modal that will allow you to write the account to which the transfer of the nft will be made, alerts were added to warn that you have to write .testnet or .near as the case may be, you are also warned if you are sure if you want to transfer the NFT to the desired account considering if the account is wrong or does not exist the NFT could be lost

NM-88 Transfer functionality added

---

src/components/statistc.component.js
src/components/transferModal.component.js
src/views/Landing.view.js
src/views/MisTokens.view.js
src/views/mintNft.view.js

Adding color to buttons on mynft cards and modals of transfer. Remove unwanted sections on landing page

New design landing page

---

src/views/gallery.js

The infinite scroll tokens obtaining method was modified to be able to bring the tokens in the reverse way (The newest NFT is shown first), the logic with which they obtain the data was accommodated, obtaining the pagination correctly

Reverse pagination

---

src/translations/en/global.json
src/translations/es/global.json
src/views/mintNft.view.js
tailwind.config.js

The possibility of adding royalties when creating an NFT was added, for this the necessary components were added in the frontend to be able to implement it together with its corresponding alerts to verify that the entire process is carried out correctly.

Add royalties when creating an NFT

---

src/translations/en/global.json
src/translations/es/global.json
src/views/Detail.view.js

Added royalty and creator information to the detail view showing current NFT information

added royalties and creator to detail view

---

src/components/Hero.component.js
src/components/imageSlider.component.js
src/translations/en/global.json
src/translations/es/global.json
tailwind.config.js

Styling First Section of landing page

New design landing page First Section

---

src/components/approvalModal.component.js
src/components/priceModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/utils/near_interaction.js
src/views/MisTokens.view.js

The functionalities of putting up for sale, removing from sale and changing the price of an NFT have been added, these methods can now be consumed to perform these actions, some are called directly in the minter contract, while in another how to change price it is necessary to make an external call directly to the marketplace contract to perform this action, in one of the functions to be able to perform the approval to the marketplace it was necessary to create an environment variable so that the marketplace contract is hidden from view in the code, It is necessary to create an environment variable for this, this variable is named REACT_APP_CONTRACT_MARKET, and for my local tests I am using this marketplace contract v1.nativo-market.testnet, the translation of all the elements that have …

Put on sale, remove from sale and change price added

---

src/translations/en/global.json
src/translations/es/global.json

The text was changed to enter the sale gallery, it was changed from on sale to market

text in navbar changed

---

src/components/approvalModal.component.js
src/views/MisTokens.view.js
src/views/salesGallery.js

The data sent to the blockchain was updated to be able to store the metadata of the token to be able to view it in the Market, the market gallery was also updated to show the image and the title of the NFT

NFT market update

---

src/components/approvalModal.component.js
src/views/MisTokens.view.js

The description of the token is sent to be stored in the marketplace and to be able to report to the graph through a log

The description is stored in the marketplace

---

src/views/salesGallery.js
tailwind.config.js

Adding style to market view

---

src/views/gallery.js

Adding style to gallery view

---

src/App.js
src/components/Navbar.component.js
src/components/approvalModal.component.js
src/components/offerModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/views/Detail.view.js

The implementation of the offers was carried out, offers can be made to nfts that are for sale, we can also make offers to tokens that are not listed in the marketplace, the relevant validations were carried out for this process, possible bugs were also prevented by send a very large number from frontend

NM-45 Implementation of bids

---

src/components/offerModal.component.js

The validation of the offer was eliminated, it must be less than the purchase price.
The validation in frontend was eliminated, until now the validation in the contract needs to be changed

Offer validation removed

---

src/components/Trendings.component.js

Fix trendings on nativo landing

Fix trendings on nativo landing

---

src/components/approvalModal.component.js
src/components/modalSubasta.component.js
src/components/priceModal.component.js
src/components/transferModal.component.js
src/views/Detail.view.js
src/views/MisTokens.view.js
src/views/gallery.js
src/views/salesGallery.js
tailwind.config.js

The detail view of an NFT was redesigned, changing the colors and shapes of the text fields according to the marketing proposal, some visual bugs were also fixed with some elements on the gallery and market screens. Some bugs were also fixed that had to do with the manner of putting an NFT up for sale and changing the price of an NFT.

NM-93 Detail view redesign

---

src/components/offerModal.component.js

Changed the color of the text in the bid modal since it was not visible

Fixed not visible text in offer modal

---

src/components/approvalModal.component.js
src/components/priceModal.component.js
src/components/transferModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/views/MisTokens.view.js
tailwind.config.js

My nfts view styling

---

src/views/Detail.view.js

fix overlapping image on mobile on detail view

Image spacing on mobile

---

src/components/priceModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/views/MisTokens.view.js

The validation was added to launch an alert in case you want to update the price of an NFT with the price it currently has, the alert was added and its corresponding text was translated.

Added validation of the same price to the price change modal

---

src/components/offerModal.component.js
src/views/Detail.view.js

Fonts my nfts view

---

src/components/Navbar.component.js
src/translations/en/global.json
src/translations/es/global.json

user profile includes:  Menu redesign to include name and picture of user, logout and profile option (view of profile still pending)

User profile

---

src/App.js
src/translations/en/global.json
src/translations/es/global.json
src/views/profile.js
src/views/profileData.js

The views of creating, editing and viewing a user's profile were added, all the information is stored in the graph and retrieved through its api, if no user information stored in the graph is detected, the user is sent to the view of create profile to store your information.

NM-83 Design the user profile interface

---

package.json
src/translations/en/global.json
src/translations/es/global.json
src/utils/near_interaction.js
src/views/MisTokens.view.js

Change the view of my Nfts to include a tab that shows my creations, this means all nfts that I've created even if I'm not current the owner

My nfts split page

---

src/views/Detail.view.js

The button to decline the offer by the owner of the token was removed, this to update with the new changes in the market, the process of accepting the offer was also changed according to the new changes in the market contract

Removed the button to decline offer and changed the process of accept offer

---

src/App.js
src/components/Navbar.component.js
src/views/profile.js

The access route to the profile has been modified, now the new route asks as a parameter the account of the user whose profile is to be accessed, the modification was also made in case it isn't the profile of the person who has started the session doesn't show the configuration buttons.

The route to access the profile was modified

---

src/views/profile.js

The routing to the create profile page was corrected, for this the line where the href is was modified

hotfix route create profile

---

src/components/addTokenModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/views/Detail.view.js

In the profile view, a button was added to open the modal where the user will be allowed to select a collection to be able to add a token already mined on the platform, if the user does not have collections in the modal, a button will appear to go to the screen to create a collection, there is validation from the frontend that the button does not appear in 2 situations, if you aren't the creator of the NFT the button will not appear, if the NFT has already been added to a collection the button will not appear either.

Created Modal to add NFTs to collections

---

src/tailwind.css
src/translations/en/global.json
src/translations/es/global.json
src/views/collectionGallery.js
tailwind.config.js

Adding gallery of collections view

Nm11 collections gallery

---

src/App.js
src/components/Navbar.component.js
src/translations/en/global.json
src/translations/es/global.json
src/views/tokensCollection.js

The view where the detail of a collection is shown has been updated to be able to receive updated information from the graph, the previous pagination method was modified to infinite scroll to adapt it to the one currently used throughout the site, the colors of the view to be able to be according to the current design of the page.
the route was updated to be able to create a collection.

Updated the view of the collection detail

---

src/translations/en/global.json
src/translations/es/global.json
src/views/collectionGallery.js

Adding translations to the card

Addins translations to the card

---

src/components/Navbar.component.js
src/translations/en/global.json
src/translations/es/global.json

Menu to not logged users on mobile

Menu onmobile

---

src/translations/en/global.json
src/translations/es/global.json
src/views/collectionGallery.js

Adding the feature to search collections by title or account on collections gallery view

Search on collections

---

src/views/MisTokens.view.js
src/views/collectionGallery.js
src/views/gallery.js
src/views/salesGallery.js
src/views/tokensCollection.js

Added a delay function in the galleries to avoid request overload to the fleek gateway, 750ms was added to each method of loading new tokens

Added 750ms for loading new images Fleek Gateway

---

src/translations/en/global.json
src/translations/es/global.json
src/views/MisTokens.view.js

Showing my collections tab on mynft

My collections on my nfts

---

src/components/Navbar.component.js
src/components/Trendings.component.js
src/views/AuctionGaleria.view.js
src/views/Detail.view.js
src/views/Galeria.view.js
src/views/MisTokens.view.js
src/views/Perfil.view.js
src/views/SendAuction.view.js
src/views/auction.view.js
src/views/collectionGallery.js
src/views/createColl.js
src/views/gallery.js
src/views/profile.js
src/views/profileData.js
src/views/salesGallery.js
src/views/tokensCollection.js

All the URLs of the fleek gateway were changed for those of the dedicated pinata gateway, the new gateway has as a link: nativonft.mypinata.cloud/ipfs/
I made the wrong branch when making the comit :c

Pinata gateway tests

---

amplify.yml
package.json

Changed the files for the Node 16 update, changed the amplify file to update the node version to 16.14.2, and updated the postCSS and tailwindCss packages in the package

Changed files for Node 16 upgrade

---

src/views/MisTokens.view.js

Filter contracts when I don't have nfts on my nfts view

Fix for contracts with errors on getting all mynfts

---

src/components/searchNftsModal.component.js
src/translations/en/global.json
src/translations/es/global.json
src/utils/near_interaction.js

Showing alert when there is no result in finding nft byid

Nm 119/fixing bugs collections

---

src/views/profileData.js

the fleek API was changed to the pinata API to upload files, the chage affect create and edit profiles

the fleek API was changed to the pinata API to upload files

---

src/utils/near_interaction.js

Adding err manage

---

src/App.js
src/components/Footer.component.js
src/components/Navbar.component.js
src/translations/en/global.json
src/translations/es/global.json
src/views/Detail.view.js
src/views/createColl.js
src/views/profile.js
src/views/tokensCollection.js

The functionality of editing the collections was added where it already allows editing the information that is stored in the graph, for this the edit collection button was added in its detail, the create collection screen was modified to be able to edit it always and when its corresponding route is used to carry out the process.
Translations were added to the buttons and messages that were executed when pressing the button to add NTVs to my wallet.
The detail of the NFTs was also modified, it was shown again .near or .testnet depending on the case of the network, in the names of the users.

Edit collections, translation of NTV button messages

---

.env.local.example
src/translations/en/global.json
src/translations/es/global.json
src/views/MisTokens.view.js
src/views/collectionGallery.js
src/views/createColl.js
src/views/tokensCollection.js

The missing translations and signs were added to be able to see if a collection is visible.
The queries in the collections gallery were modified to only show the collections that have the visibility status set to true, even so, the non-visible collections can be viewed through the search in the gallery or through the sections of my collections in my NFTs.
The edit collection button was added in the my collections section within my NFTs so that it will no longer be necessary to enter the collection to be able to edit the collection.

Added translations to edit collection and collection visibility section

---

src/components/addTokenModal.component.js
src/components/approvalModal.component.js
src/components/offerModal.component.js
src/components/priceModal.component.js
src/components/transferModal.component.js
src/tailwind.css
src/views/Detail.view.js
src/views/MisTokens.view.js
src/views/createColl.js
src/views/mintNft.view.js
src/views/profileData.js
src/views/tokensCollection.js

The styles of the main buttons of the site were changed, which allow access to other sections or carry out transactions with the blockchain, the styles were changed so that the buttons have a glow and if you go over them, your button becomes bigger and stronger. color.

Change of style of the main buttons of the site

---

.env.local.example
src/App.js
src/components/Footer.component.js
src/components/Navbar.component.js
src/components/addTokenModal.component.js
src/components/approvalModal.component.js
src/components/offerModal.component.js
src/components/priceModal.component.js
src/components/transferModal.component.js
src/tailwind.css
src/translations/en/global.json
src/translations/es/global.json
src/views/Detail.view.js
src/views/MisTokens.view.js
src/views/collectionGallery.js
src/views/createColl.js
src/views/mintNft.view.js
src/views/profile.js
src/views/profileData.js
src/views/tokensCollection.js

Reverts cloudmex/Nativo-NFT-UI#97

Revert "Merging develop to main to include the visibility field in create collections "

---

.env.local.example
src/App.js
src/components/Footer.component.js
src/components/Navbar.component.js
src/components/addTokenModal.component.js
src/components/approvalModal.component.js
src/components/offerModal.component.js
src/components/priceModal.component.js
src/components/transferModal.component.js
src/tailwind.css
src/translations/en/global.json
src/translations/es/global.json
src/views/Detail.view.js
src/views/MisTokens.view.js
src/views/collectionGallery.js
src/views/createColl.js
src/views/mintNft.view.js
src/views/profile.js
src/views/profileData.js
src/views/tokensCollection.js

This reverts commit b8422fd89e2508b2d262b7a16428baee7643355d.

Revert "Revert "Merging develop to main to include the visibility field in create collections ""

---

src/views/collectionGallery.js

It was added to the query of the collections screen that only those that have more than 0 tokens registered in the collection are shown

Added a filter parameter to the collection gallery query

---

src/translations/en/global.json
src/translations/es/global.json
src/views/createColl.js

Added redirection to the myNFTs page or to the collection once the create or edit collection transaction has been executed.

Added redirection after creating or editing a collection

---

src/translations/en/global.json
src/translations/es/global.json
src/views/collectionGallery.js

The redesign of the collections gallery was carried out according to the changes that were made in the google docs document, the design of the collection cards was changed in addition to the number of cards that are shown, the style of the search bar was modified so that it takes more space on the screen, the button to clear the search was removed and it restarts as long as the search bar is cleared after having made a search

Collection gallery redesign

---

src/components/Hero.component.js
src/components/NftSteps.component.js
src/components/statistc.component.js
src/tailwind.css
src/views/community.js

Fixed the size of the first section of the landing page so that it covers the entire screen.

fix: size of first section of landing page.

---

src/translations/en/global.json
src/translations/es/global.json
src/views/salesGallery.js

the redesign of the token gallery in the market was carried out, the design of the cards of the site was changed in addition to adding the title of the page at the top

market gallery redesign

---

src/components/Trendings.component.js
src/views/MisTokens.view.js
src/views/tokensCollection.js

Updated card design on missing parts of the site, myNfts, tokenCollection and trendings
In my NFTs, the cards of the collections were updated by changing one of the data for the collection ID, with that it will be possible to distinguish between the repeated collections.
In trendings and tokensCollection the design of the cards was updated so that the site has the same design at least in those sections

Card design update

---

package.json
src/components/Footer.component.js
src/translations/en/global.json
src/translations/es/global.json

The links to the site documentation in the footer were updated, in addition to adding new ones such as the NFTs license and the privacy and creativity policies.
Also added latest stable version of modal-ui

Update of documentation links in the footer

---

public/index.html
tailwind.config.js

Adding new global fonts and tailwind config on site

adding fonts

---

public/index.html

Title, description and keywords tags have been updated to focus on the report that was previously sent

Title, description and keywords tags have been updated

---

public/index.html
src/App.js
src/components/Footer.component.js
src/components/Navbar.component.js
src/components/NftSteps.component.js
src/components/Trendings.component.js
src/components/statistc.component.js
src/index.js
src/views/Detail.view.js
src/views/collectionGallery.js
src/views/community.js
src/views/createColl.js
src/views/gallery.js
src/views/mintNft.view.js
src/views/profile.js
src/views/profileData.js
src/views/tokensCollection.js

Given the reports and notes that we were making about SEO, it was seen that some images on the site did not contain the alt, it was added to the remaining images.
With the page speed annotations, the UL tag was added to the li tags since it marked that missing part, lowering the score.
The default language of the site was changed to English, for this the button to change language was added in the footer

The alt was added to the images, the UL was added to the li tags, the default language of the site was changed to English

---

src/components/NftStepsCard.component.js
src/components/PopularCollections.component.js
src/components/Trendings.component.js
src/components/statistc.component.js
src/tailwind.css

Changes to landing page:
-  Sorting to collections sections and tokens
-  Update delay on steps section
-  Styling cards
-  redirect to Nativo DAO button

Changes to landing page

---

src/views/explore.view.js

The error was corrected when entering a collection from explore, the route was changed and it was resolved

The route of the collections in explore was changed

---

src/tailwind.css

Fix the click on the half of screen

fix menu mobile click

---

src/translations/es/global.json
src/views/profile.js

Added the translate in spanish for the Profile.upimg4 field 
Added a validation in the profile Edit's button to determinate
if the route is /create or /edit

were fixed:
